name: CI Pokedex Vue

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar
        uses: actions/checkout@v3

      - name: Configurar
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar
        run: npm install

      - name: Testes
        run: npx vitest

      - name: Buildar
        run: npm run build
